language: ruby
rbenv:
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode
  - 1.8.7
  
notifications:
  email:
    recipients:
      - luong.minh@mulodo.com
    on_success: [always] # default: change
    on_failure: [always] # default: always
